### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Giuliagiorgi** [YaleDHLab/pix-plot#188]
Good afternoon, I get this problem when parsing the metadata with tags (it works when I delete the "tags" column). 

```
Using TensorFlow backend.
2021-05-06 14:05:25.842563: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
Device mapping: no known devices.
2021-05-06 14:05:26.131387: I tensorflow/core/common_runtime/direct_session.cc:296] Device mapping:

Traceback (most recent call last):
  File "c:\users\giulia\anaconda3\envs\3.6\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\giulia\anaconda3\envs\3.6\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Giulia\Anaconda3\envs\3.6\Scripts\pixplot.exe\__main__.py", line 7, in <module>
  File "c:\users\giulia\anaconda3\envs\3.6\lib\site-packages\pixplot\pixplot.py", line 1360, in parse
    process_images(**config)
  File "c:\users\giulia\anaconda3\envs\3.6\lib\site-packages\pixplot\pixplot.py", line 128, in process_images
    kwargs['image_paths'], kwargs['metadata'] = filter_images(**kwargs)
  File "c:\users\giulia\anaconda3\envs\3.6\lib\site-packages\pixplot\pixplot.py", line 210, in filter_images
    l = get_metadata_list(**kwargs)
  File "c:\users\giulia\anaconda3\envs\3.6\lib\site-packages\pixplot\pixplot.py", line 308, in get_metadata_list
    l.append({headers[j]: i[j] if i[j] else '' for j, _ in enumerate(headers)})
  File "c:\users\giulia\anaconda3\envs\3.6\lib\site-packages\pixplot\pixplot.py", line 308, in <dictcomp>
    l.append({headers[j]: i[j] if i[j] else '' for j, _ in enumerate(headers)})
IndexError: list index out of range
```

Here is a snippet of the metadata file:
```
filename,year,tags,category,permalink
4a1d087266e3a07bf35b26938ea376aa.jpg,404,acqusitaonline|iorestoacasa,tumblr,https://64.media.tumblr.com/014d2fda1d495d1094359c8bd18a0940/24980a0fc387d9de-5a/s1280x1920/8914b18f98f4c98471d383e8c085e6a10d5084ce.jpg
41158615f80cb587ca860eed54237fbb.jpg,404,angolodipoesia|giusicontrafatto|iorestoacasa|leggiamolepoesie|poesia pensieri|izabellateresakostka|poetry,tumblr,https://64.media.tumblr.com/018cdedf5b0f9300063acf0b1fae760e/7e65c70a6f660fcd-c2/s1280x1920/50af8131209c6c4127ac4e1368cde368d592f27b.jpg
a439d672d9ff161b636448a0351e4175.jpg,404,iorestoacasa|marellagiovannelli|bioscalin|sprayritocco|capelli|restiamoacasa|consiglioutile|quarantena|alleanza|esperimento|ricrescitacapelli,tumblr,https://64.media.tumblr.com/01dea4fb4be828344ba026763e20f8df/ce213adfcb3b17e5-d5/s1280x1920/6c3bcbd549a12b2b69973a5f89f2111b1c395e52.jpg
```

I am using the latest version of Pixplot with py 3.6 (3.7 also shows this issue) on Windows 10.
Is it because I have too many tags per image?

Thank you very much,
GG

**Comment by duhaime** [comment]
@Giuliagiorgi Many thanks for reaching out! I have a hunch that somewhere in your CSV, there are one or more rows with fewer than 5 columns. 

I just merged a commit that should prevent that error from springing though--if you reinstall and try again, do you have more luck?

**Comment by Giuliagiorgi** [comment]
Thank you for your fast reply! 
It works perfectly now :) Thank you again, Giulia

**Comment by duhaime** [comment]
Wonderful, thanks for the follow up @Giuliagiorgi!
