### ISSUE TITLE
Requirments Issue

### ISSUE THREAD

**Issue by haylie-murray** [YaleDHLab/pix-plot#253]
I currently am using tensorflow==2.5.3 and using numpy==1.19.5
but once I try to run the command for pixplot;

I get this error:
`Using TensorFlow backend.
Traceback (most recent call last):
  File "/opt/conda/bin/pixplot", line 5, in <module>
    from pixplot import parse
  File "/opt/conda/lib/python3.7/site-packages/pixplot/__init__.py", line 2, in <module>
    from pixplot.pixplot import process_images, parse
  File "/opt/conda/lib/python3.7/site-packages/pixplot/pixplot.py", line 23, in <module>
    from hdbscan import HDBSCAN
  File "/opt/conda/lib/python3.7/site-packages/hdbscan/__init__.py", line 1, in <module>
    from .hdbscan_ import HDBSCAN, hdbscan
  File "/opt/conda/lib/python3.7/site-packages/hdbscan/hdbscan_.py", line 21, in <module>
    from ._hdbscan_linkage import (single_linkage,
  File "hdbscan/_hdbscan_linkage.pyx", line 1, in init hdbscan._hdbscan_linkage
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject`

Am I using the wrong tensorflow and numpy?

**Comment by lakonis** [comment]
similar problem with `hdscan` on my side. 
Uptodate version of hdbscan fails to work : `pkg_resources.DistributionNotFound: The 'numpy==1.19.5' distribution was not found and is required by pixplot`

So i retrograde numpy and hdbscan : `numpy==1.19.5` `hdbscan==0.8.24`, but then pixplot does not find it : `HDBSCAN not available; using sklearn KMeans`

Using `tensorflow=2.5.0`
