### ISSUE TITLE
HDBSCAN not available

### ISSUE THREAD

**Issue by lakonis** [YaleDHLab/pix-plot#266]
Hello, I have the following packages running python 3.7.16:

```bash
tensorflow                     2.5.0
numpy                          1.19.5
hdbscan                        0.8.24
pixplot                        0.0.113
```
yet, pixplot gives me the following error when accessing my dataset and metadata csv:

```bash
2023-03-22 17:53:45.147839: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2023-03-22 17:53:45.147862: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2023-03-22 17:53:46.145373: HDBSCAN not available; using sklearn KMeans
2023-03-22 17:53:49.159517: CUML not available; using umap-learn UMAP
2023-03-22 17:53:49.159901: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-03-22 17:53:49.161109: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2023-03-22 17:53:49.161125: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)
2023-03-22 17:53:49.161142: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (nicolas-hpeb830g8): /proc/driver/nvidia/version does not exist
2023-03-22 17:53:49.161469: I tensorflow/core/common_runtime/direct_session.cc:361] Device mapping: no known devices.
```

I don't understand the errors neither why `HDBSCAN is not available`

Thanks for your help!

**Comment by pleonard212** [comment]
Interesting -- if you start Python and try:
```
import hdbscan
```
...do you get no response (which is good!) or an error?

**Comment by lakonis** [comment]
Error indeed : 

```bash
python                                                                                                               ✔  12h 10m 45s   3.7.16  
Python 3.7.16 (default, Mar 22 2023, 16:00:53) 
[GCC 12.2.1 20230201] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import hdbscan
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nicolas/.pyenv/versions/3.7.16/lib/python3.7/site-packages/hdbscan/__init__.py", line 1, in <module>
    from .hdbscan_ import HDBSCAN, hdbscan
  File "/home/nicolas/.pyenv/versions/3.7.16/lib/python3.7/site-packages/hdbscan/hdbscan_.py", line 21, in <module>
    from ._hdbscan_linkage import (single_linkage,
  File "hdbscan/_hdbscan_linkage.pyx", line 1, in init hdbscan._hdbscan_linkage
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
```

**Comment by lakonis** [comment]
I believe it has something to do with `tensorflow`, `cuda`, `libcudart.so.11.0`, etc. I am not sure I want to go that deep since I am using pixplot for ~1000 images dataset. 

However, it seems that hdbscan takes into account the label/category column into the clustering, which is particularly interesting in my case. I believe the `sklearn KMeans` does not, is that correct ?

Am I missing something else without CUML ?

```
HDBSCAN not available; using sklearn KMeans
CUML not available; using umap-learn UMAP
```

Thank you !

**Comment by pleonard212** [comment]
CUML is just a library that contains an accelerated implementation of UMAP; no worries there.  You're correct that there are some real annoyances around numba and numpy; not sure if you're on Linux or not but there's some notes on the very end of this wiki page that might help:

[https://github.com/YaleDHLab/pix-plot/wiki/Ubuntu-20-&-22-with-GPU](https://github.com/YaleDHLab/pix-plot/wiki/Ubuntu-20-&-22-with-GPU)

**Comment by lakonis** [comment]
I am on Linux Manjaro, but I have a GPU Intel. Therefore, I am trying [this](https://www.tensorflow.org/install/gpu_plugins?hl=en#use_device_plugins), installing [intel-extension-for-tensorflow 1.1.0](https://pypi.org/project/intel-extension-for-tensorflow/), but it upgrades everything and breaks pixplot requirements.

Again, GPU or speed is not crucial to me. It's rather hdbscan that could improve my clustering from what I understand. But maybe I am mistaking ?

**Comment by nabsiddiqui** [comment]
I was able to get it to work with the following:

```
pip install hdbscan==0.8.31
pip install 'urllib3<2.0'
pip install https://github.com/yaledhlab/pix-plot/archive/master.zip
```

**Comment by mradamcox** [comment]
I am on Ubuntu 22 (PopOS) and had success with `hdbscan==0.8.33` but not the latest version (`0.8.40`) nor `0.8.31`.
