### ISSUE TITLE
Sample data downloads are broken

### ISSUE THREAD

**Issue by BradNeuberg** [YaleDHLab/pix-plot#278]
Looks like the pixplot.yale.edu domain is down, making it impossible to get the sample data:

```
$ python
Python 3.8.18 (default, Sep 11 2023, 08:17:33)
[Clang 14.0.6 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import image_datasets

image_datasets.oslomini.download()
>>>
>>> image_datasets.oslomini.download()
 * downloading oslomini metadata from http://pixplot.yale.edu/datasets/oslomini/metadata.csv


Traceback (most recent call last):
  File "/Users/bradneuberg/opt/anaconda3/envs/pixplot/lib/python3.8/site-packages/urllib3/connection.py", line 203, in _new_conn
    sock = connection.create_connection(
  File "/Users/bradneuberg/opt/anaconda3/envs/pixplot/lib/python3.8/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/Users/bradneuberg/opt/anaconda3/envs/pixplot/lib/python3.8/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 60] Operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/bradneuberg/opt/anaconda3/envs/pixplot/lib/python3.8/site-packages/urllib3/connectionpool.py", line 791, in urlopen
    response = self._make_request(
  File "/Users/bradneuberg/opt/anaconda3/envs/pixplot/lib/python3.8/site-packages/urllib3/connectionpool.py", line 497, in _make_request
    conn.request(
  File "/Users/bradneuberg/opt/anaconda3/envs/pixplot/lib/python3.8/site-packages/urllib3/connection.py", line 395, in request
    self.endheaders()
  File "/Users/bradneuberg/opt/anaconda3/envs/pixplot/lib/python3.8/http/client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Users/bradneuberg/opt/anaconda3/envs/pixplot/lib/python3.8/http/client.py", line 1011, in _send_output
    self.send(msg)
  File "/Users/bradneuberg/opt/anaconda3/envs/pixplot/lib/python3.8/http/client.py", line 951, in send
    self.connect()
  File "/Users/bradneuberg/opt/anaconda3/envs/pixplot/lib/python3.8/site-packages/urllib3/connection.py", line 243, in connect
    self.sock = self._new_conn()
  File "/Users/bradneuberg/opt/anaconda3/envs/pixplot/lib/python3.8/site-packages/urllib3/connection.py", line 218, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f92d11e27f0>: Failed to establish a new connection: [Errno 60] Operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/bradneuberg/opt/anaconda3/envs/pixplot/lib/python3.8/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/Users/bradneuberg/opt/anaconda3/envs/pixplot/lib/python3.8/site-packages/urllib3/connectionpool.py", line 845, in urlopen
    retries = retries.increment(
  File "/Users/bradneuberg/opt/anaconda3/envs/pixplot/lib/python3.8/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='pixplot.yale.edu', port=80): Max retries exceeded with url: /datasets/oslomini/metadata.csv (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f92d11e27f0>: Failed to establish a new connection: [Errno 60] Operation timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/bradneuberg/opt/anaconda3/envs/pixplot/lib/python3.8/site-packages/image_datasets/core.py", line 27, in download
    self.save(metadata_path, self.metadata_path, blocksize=blocksize)
  File "/Users/bradneuberg/opt/anaconda3/envs/pixplot/lib/python3.8/site-packages/image_datasets/core.py", line 48, in save
    r = requests.get(url, allow_redirects=True)
  File "/Users/bradneuberg/opt/anaconda3/envs/pixplot/lib/python3.8/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/Users/bradneuberg/opt/anaconda3/envs/pixplot/lib/python3.8/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/bradneuberg/opt/anaconda3/envs/pixplot/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/bradneuberg/opt/anaconda3/envs/pixplot/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/Users/bradneuberg/opt/anaconda3/envs/pixplot/lib/python3.8/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='pixplot.yale.edu', port=80): Max retries exceeded with url: /datasets/oslomini/metadata.csv (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f92d11e27f0>: Failed to establish a new connection: [Errno 60] Operation timed out'))
```

**Comment by jthiels** [comment]
Any update on this?  Also getting this error

**Comment by duhaime** [comment]
Sorry for the radio silence. I just pushed an update. If you try:

```
pip install image_datasets --upgrade
rm -rf datasets
```

then in a Python shell:

```
import image_datasets
image_datasets.oslomini.download()
```

any luck?

**Comment by jthiels** [comment]
I was able to download the dataset.  Thanks!
