### ISSUE TITLE
Experimental: kdtree.py Troublesome data array

### ISSUE THREAD

**Issue by cncoleman** [YaleDHLab/pix-plot#91]
The #89 problem fixed and images successfully vectorized, I am getting a troublesome data array and when attempting to serve, a manifest.json file is missing.

**Comment by duhaime** [comment]
Hmm, that's intriguing. Could I ask you to `rm -rf output`, then rebuild the plot (`pixplot --images "my/*.jpg"`), and then if the kd-tree stack trace appears, copy and paste the stack trace here in full? 

The data processing pipeline uses a little internal cache, and my hunch is that the iiif error you saw caused this problem too, because it caused bad data to get cached. Chances are clearing the output directory and reprocessing will clear this up, but if not seeing the full stack trace will be helpful in figuring out what's going on...

**Comment by cncoleman** [comment]
Traceback (most recent call last):
  File "/Users/fantasticfutures2019/opt/anaconda3/envs/JanuaryExperimental/bin/pixplot", line 8, in <module>
    sys.exit(parse())
  File "/Users/fantasticfutures2019/opt/anaconda3/envs/JanuaryExperimental/lib/python3.6/site-packages/pixplot/pixplot.py", line 644, in parse
    process_images(**config)
  File "/Users/fantasticfutures2019/opt/anaconda3/envs/JanuaryExperimental/lib/python3.6/site-packages/pixplot/pixplot.py", line 84, in process_images
    get_manifest(**kwargs)
  File "/Users/fantasticfutures2019/opt/anaconda3/envs/JanuaryExperimental/lib/python3.6/site-packages/pixplot/pixplot.py", line 128, in get_manifest
    layouts = get_layouts(**kwargs)
  File "/Users/fantasticfutures2019/opt/anaconda3/envs/JanuaryExperimental/lib/python3.6/site-packages/pixplot/pixplot.py", line 345, in get_layouts
    raster = get_rasterfairy_projection(umap=umap, **kwargs)
  File "/Users/fantasticfutures2019/opt/anaconda3/envs/JanuaryExperimental/lib/python3.6/site-packages/pixplot/pixplot.py", line 421, in get_rasterfairy_projection
    paddingScale=1.05)
  File "/Users/fantasticfutures2019/opt/anaconda3/envs/JanuaryExperimental/lib/python3.6/site-packages/rasterfairy/coonswarp.py", line 94, in rectifyCloud
    return warpCloud( xyc, sourceGridPoints, targetGridPoints, warpQuality=warpQuality )
  File "/Users/fantasticfutures2019/opt/anaconda3/envs/JanuaryExperimental/lib/python3.6/site-packages/rasterfairy/coonswarp.py", line 43, in warpCloud
    sourceTree = KDTree(sourceGridPoints, leafsize=10)
  File "/Users/fantasticfutures2019/opt/anaconda3/envs/JanuaryExperimental/lib/python3.6/site-packages/scipy/spatial/kdtree.py", line 242, in __init__
    self.tree = self.__build(np.arange(self.n), self.maxes, self.mins)
  File "/Users/fantasticfutures2019/opt/anaconda3/envs/JanuaryExperimental/lib/python3.6/site-packages/scipy/spatial/kdtree.py", line 305, in __build
    raise ValueError("Troublesome data array: %s" % data)
ValueError: Troublesome data array: [nan nan nan ... nan nan nan]

**Comment by duhaime** [comment]
hmm, that's interesting. Did you get this error when trying to build a plot with iiif manifests? If so, would you be able to share your manifest file? If I could reproduce this I'd be able to figure out what went wrong. 

My hunch is still that there might have been cached data lingering that caused this. Just to check, did you run `rm -rf output` before kicking off the job that threw this error?

**Comment by cncoleman** [comment]
In this case I was **not** trying to build a plot with iiif manifests. I used a sample set of images. I ran 'rm -rf output' first. The images were vectorized. The layouts are created. I still get 
```
ValueError: Troublesome data array: [nan nan nan ... nan nan nan]
```

**Comment by duhaime** [comment]
This is interesting. Is there any chance you could share the umap projection generated by this process (before it fails)? I believe that should be persisted before this error triggers. (It'd be in `output/data/layouts/` If you can send that on I'm happy to take a look!

**Comment by cncoleman** [comment]
@duhaime I've rebuilt the VE and ran one image collection without seeing the kdtree issue. So, perhaps it was cached data, though removing /output didn't help. I'm running another collection. If it works as well, I'll close this issue. Thank you.

**Comment by duhaime** [comment]
@cncoleman curioser and curioser. If you can reproduce the issue please let me know and I'll be happy to take a look!
